apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: {{ include "capi-aws.fullname" . }}-md-0
  namespace: default
spec:
  clusterName: {{ include "capi-aws.fullname" . }}
  replicas:  {{ .Values.workers.replicas }} 
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: {{ include "capi-aws.fullname" . }}-md-0
      clusterName: {{ include "capi-aws.fullname" . }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AWSMachineTemplate
        name: {{ include "capi-aws.fullname" . }}-md-0
      version: {{ .Values.kube.version }}