apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: capi-gcp-demo-stage
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/rcompos/capi-clusters.git 
    path: charts/capi-gcp
    targetRevision: HEAD
    helm:
      valueFiles:
      - values-demo-stage.yaml
  syncPolicy: {}
