apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-dev
  namespace: argocd
spec:
  project: proj-capi-clusters
  source:
    repoURL: https://github.com/rcompos/capi-clusters.git 
    path: charts/hello-world
    targetRevision: HEAD
    helm:
      valueFiles:
      - values-dev.yaml
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy: {}
