apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: capi-azure-dev
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/rcompos/capi-clusters.git 
    path: charts/capi-azure
    targetRevision: HEAD
    helm:
      valueFiles:
      - values-dev.yaml
  syncPolicy: {}
