apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: capi-aws-eks-prod
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: proj-capi-clusters
  source:
    repoURL: https://github.com/rcompos/capi-clusters.git 
    path: charts/capi-aws-eks
    targetRevision: HEAD
    helm:
      valueFiles:
      - values-aws-eks-prod.yaml
  syncPolicy: {}
