apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: capi-aws-eks-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rcompos/capi-clusters.git 
    path: charts/capi-aws-eks
    targetRevision: main
    helm:
      valueFiles:
      - values-aws-eks-dev.yaml
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy: {}
